
=====================================>>>
Run: org.apache.harmony.jpda.tests.jdwp.MultiSession.ExceptionTest.testException001
----------------------------------------
ATTACH connector kind
[SYNC] Binding socket on port: 0
[SYNC] Bound socket on port: 4030
Attach to: 127.0.0.1:9898
Launch: D:\workingcopy\hy6\target\hdk\jdk\jre/bin/java -cp "D:\workingcopy\hy6\working_jdktools\build\tests\classes;D:\tools\apache-ant-1.7.1\lib\junit-4.1.jar;D:\tools\apache-ant-1.7.1\lib\ant-launcher.jar;D:\tools\apache-ant-1.7.1\lib\ant.jar;D:\tools\apache-ant-1.7.1\lib\ant-junit.jar" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:9898,server=y,suspend=y  -Djpda.settings.verbose=true -Djpda.settings.syncPort=4030 org.apache.harmony.jpda.tests.jdwp.Events.ExceptionDebuggee
Launch process: D:\workingcopy\hy6\target\hdk\jdk\jre/bin/java -cp "D:\workingcopy\hy6\working_jdktools\build\tests\classes;D:\tools\apache-ant-1.7.1\lib\junit-4.1.jar;D:\tools\apache-ant-1.7.1\lib\ant-launcher.jar;D:\tools\apache-ant-1.7.1\lib\ant.jar;D:\tools\apache-ant-1.7.1\lib\ant-junit.jar" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:9898,server=y,suspend=y  -Djpda.settings.verbose=true -Djpda.settings.syncPort=4030 org.apache.harmony.jpda.tests.jdwp.Events.ExceptionDebuggee
Splitted command line: [D:\workingcopy\hy6\target\hdk\jdk\jre/bin/java, -cp, D:\workingcopy\hy6\working_jdktools\build\tests\classes;D:\tools\apache-ant-1.7.1\lib\junit-4.1.jar;D:\tools\apache-ant-1.7.1\lib\ant-launcher.jar;D:\tools\apache-ant-1.7.1\lib\ant.jar;D:\tools\apache-ant-1.7.1\lib\ant-junit.jar, -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:9898,server=y,suspend=y, -Djpda.settings.verbose=true, -Djpda.settings.syncPort=4030, org.apache.harmony.jpda.tests.jdwp.Events.ExceptionDebuggee]
Launched process
Start redirectors
Redirector started: STDERR
Redirector started: STDOUT
Started redirectors
Launched debuggee process
Attaching for JDWP connection
STDOUT> Listening for transport dt_socket at address: 9898
Established transport connection
Established JDWP connection with debuggee VM
Received inital VM_INIT event
Adjusted VM-dependent type lengths
Resumed debuggee VM
[SYNC] Accepting socket connection
STDOUT> [SYNC] Attaching socket to: localhost:4030
[SYNC] Accepted socket connection
Established sync connection
----------------------------------------
>> testException001: STARTED...
[SYNC] Waiting for message: ready
[SYNC] Received message: ready

>> testExceptionEvent: => setException(...)...
STDOUT> [SYNC] Attached socket
STDOUT> -- ExceptionDebuggee: STARTED
STDOUT> [SYNC] Message sent: ready
STDOUT> -- ExceptionDebuggee: Wait for SGNL_CONTINUE...
STDOUT> [SYNC] Waiting for message: continue
>> testExceptionEvent: setException(...) DONE

=> CLOSE CONNECTION
STDERR> 14:51:57.609 ERROR: [PacketDispatcher.cpp:137] Run: Exception in reading command: TransportException [510/202] close socket failed (error code: -241)
Closed transport connection
=> CONNECTION CLOSED

=> OPEN NEW CONNECTION
Attaching for JDWP connection
Opened transport connection
Adjusted VM-dependent type lengths
=> CONNECTION OPENED
=> Resuming debuggee
STDOUT> [SYNC] Received message: continue
STDOUT> -- ExceptionDebuggee: SGNL_CONTINUE has been received!
STDOUT> -- ExceptionDebuggee: Exception: "Caught debuggee exception" was thrown
STDOUT> DUMP{org.apache.harmony.jpda.tests.jdwp.Events.DebuggeeException: dummy exception}
STDOUT> -- ExceptionDebuggee: FINISHing...
STDOUT> [SYNC] Closed socket
[SYNC] Message sent: continue
[SYNC] Waiting for message: ready
=> Wait for event..
=> Received event set: count=1
=> Event #0;
=> SuspendPolicy=0/NONE
=> EventKind=99/VM_DEATH
=> RequestID=0
=> found auto VM_DEATH event!
==> testException001 PASSED!
----------------------------------------
[SYNC] Closed socket
Completed sync connection
Waiting for process exit
Redirector completed: STDERR
Redirector completed: STDOUT
Finished debuggee with exit code: 0
Finished process
Waiting for redirectors finish
Finished redirectors
Closed JDWP connection with debuggee VM
<<<=====================================


