
=====================================>>>
Run: org.apache.harmony.jpda.tests.jdwp.Events.FieldAccessTest.testFieldAccessEvent
----------------------------------------
[SYNC] Binding socket on port: 0
org.apache.harmony.jpda.tests.framework.TestErrorException: [SYNC] Exception in binding for socket sync connection
	at org.apache.harmony.jpda.tests.share.JPDADebuggeeSynchronizer.bindServer(JPDADebuggeeSynchronizer.java:183)
	at org.apache.harmony.jpda.tests.jdwp.share.JDWPSyncTestCase.beforeDebuggeeStart(JDWPSyncTestCase.java:45)
	at org.apache.harmony.jpda.tests.jdwp.share.JDWPTestCase.internalSetUp(JDWPTestCase.java:60)
	at org.apache.harmony.jpda.tests.jdwp.share.JDWPSyncTestCase.internalSetUp(JDWPSyncTestCase.java:62)
	at org.apache.harmony.jpda.tests.jdwp.share.JDWPRawTestCase.setUp(JDWPRawTestCase.java:94)
	at junit.framework.TestCase.runBare(TestCase.java:128)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:228)
	at junit.framework.TestSuite.run(TestSuite.java:223)
	at org.junit.internal.runners.OldTestClassRunner.run(OldTestClassRunner.java:35)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:32)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:743)
Caused by: java.net.BindException: The address is already in use
	at org.apache.harmony.luni.platform.OSNetworkSystem.bind(OSNetworkSystem.java)
	at org.apache.harmony.luni.net.PlainSocketImpl.bind(PlainSocketImpl.java:178)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at java.net.ServerSocket.<init>(ServerSocket.java:79)
	at org.apache.harmony.jpda.tests.share.JPDADebuggeeSynchronizer.bindServer(JPDADebuggeeSynchronizer.java:177)
	at org.apache.harmony.jpda.tests.jdwp.share.JDWPSyncTestCase.beforeDebuggeeStart(JDWPSyncTestCase.java:45)
	... 15 more
----------------------------------------
[SYNC] Closed socket
Completed sync connection
Ignoring exception in disposing debuggee VM: java.lang.NullPointerException

